# Generated by Django 2.0.2 on 2018-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='域名')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='主机记录')),
                ('type', models.CharField(choices=[('0', 'A'), ('1', 'CNAME'), ('2', 'MX'), ('3', 'NS'), ('4', 'AAAA'), ('5', 'URL显性'), ('6', 'URL隐性'), ('7', 'SRV记录')], max_length=2, verbose_name='记录类型')),
                ('value', models.CharField(max_length=255, verbose_name='记录值')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级')),
                ('domain', models.ForeignKey(on_delete='CASCADE', related_name='records', to='dns.Domain', verbose_name='域名')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('host', 'domain', 'type', 'value', 'priority')},
        ),
    ]
