# Generated by Django 2.0.2 on 2018-02-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='域名')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='主机记录')),
                ('value', models.CharField(max_length=255, verbose_name='记录值')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级')),
                ('domain', models.ForeignKey(on_delete='CASCADE', related_name='d_records', to='dns.Domain', verbose_name='域名')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='类型')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete='CASCADE', related_name='t_records', to='dns.Type', verbose_name='记录类型'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('host', 'domain', 'type', 'value', 'priority')},
        ),
    ]
